# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: pureuda-os
description: "Pureuda OS is an experimental Linux image forked from Origami Linux. Based on Fedora Cosmic Atomic, powered by grapes."
base-image: ghcr.io/blue-build/base-images/fedora-cosmic
image-version: latest
#blue-build-tag: main

platforms:
  - linux/amd64

modules:
  - from-file: bootstrap.yml

  - type: custom-kernel
    source: local
    kernel: cachyos-lto
    initramfs: true
    secrets:
      - type: file
        source: .secure_files/MOK.priv
        mount:
          type: file
          destination: /tmp/certs/MOK.priv
    sign:
      key: /tmp/certs/MOK.priv
      cert: /usr/share/cert/MOK.pem
      mok-password: bluebuild

  - from-file: core.yml

  - type: os-release
    properties:
      ID: pureuda-os
      ID_LIKE: fedora
      NAME: Pureuda OS
      PRETTY_NAME: "Pureuda OS 2026.03"
      HOME_URL: "https://github.com/Pandabrain/pureuda-os/"
      BUG_REPORT_URL: "https://github.com/Pandabrain/pureuda-os/issues"
      DEFAULT_HOSTNAME: pureuda-os

  - from-file: finalize.yml
