---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: pureuda-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      cleanup: true 
      files:
        - https://repo.vivaldi.com/archive/vivaldi-fedora.repo
      keys:
        - https://repo.vivaldi.com/archive/linux_signing_key.pub
        - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
        - https://dl.google.com/linux/linux_signing_key.pub

    install:
      packages:
        - codium
        - vivaldi-stable
        - google-chrome-stable
        - git
        - cmake
        - ninja-build
        - gtk3-devel
        - mesa-libGLU-devel
#        - micro
#        - starship
#    remove:
#      packages:
#        # example: removing firefox (in favor of the flatpak)
#        # "firefox" is the main package, "firefox-langpacks" is a dependency
#        - firefox
#        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
  - type: script
    scripts:
      - install-proton-vpn.sh
      - install-proton-pass.sh
      - install-proton-mail.sh
      - set-fish-shell.sh
      - install-jetbrains-toolbox.sh
      - install-joplin.sh
      - install-flutter.sh
      - install-audacity.sh
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
#        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
#          - org.mozilla.firefox
#          - org.gnome.Loupe
           - org.gnome.Calculator
           - com.discordapp.Discord
           - org.jellyfin.JellyfinDesktop
           - org.telegram.desktop
           - org.libreoffice.LibreOffice
           - com.github.tchx84.Flatseal
           - io.github.kolunmi.Bazaar
           - io.github.flattool.Warehouse
           - com.ranfdev.DistroShelf
           - io.podman_desktop.PodmanDesktop
           - org.kde.haruna
           - org.inkscape.Inkscape
           - org.gimp.GIMP
           - org.freecad.FreeCAD
           - org.deskflow.deskflow
           - com.bambulab.BambuStudio
        remove:
          - org.mozilla.Thunderbird
          - org.kde.kontakt
          - org.kde.kcalc
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
