stages:
  - triggers
default:
  interruptible: true
workflow:
  rules:
    - if: $GITLAB_CI_ENABLED != "true"
      when: never
    - if: $CI_COMMIT_BRANCH == "main" || $CI_PIPELINE_SOURCE == "schedule" || $CI_COMMIT_TAG
      changes:
        - "**/*"
        - "!README.md"
    - when: never

# --- Trigger Base Pipeline ---
trigger-base-image-build:
  stage: triggers
  trigger:
    include: .gitlab-ci-base.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - recipes/base.yml
        - recipes/core.yml
        - .gitlab-ci-base.yml
        - .gitlab-ci.yml
        - "files/**/*"
        - "modules/**/*"
