name: bluebuild
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name}}
  cancel-in-progress: true
on:
  schedule:
    - cron: "0 6 * * *"
    - cron: "12 12 * * *"
  #push:
    #branches:
    #  - main
    #  - test
    #paths-ignore:
    #  - "**.md"
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: docker
    container:
      image: ghcr.io/blue-build/cli:latest
      #options: --user root #-v /var/run/docker.sock:/var/run/docker.sock
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - base.yml
    steps:
      - name: Install node
        run: |
          dnf install -y nodejs

      - name: Checkout repository
        uses: actions/checkout@v6

      #if nodejs installation or the checkout action should fail, you can simply replace the installation of nodejs and the checkout action above
      # and just run git commands manually like so:
      #      - name: Checkout repository
      #        run: |
      #          git clone ${{ github.server_url }}/${{ github.repository }} .
      #          git checkout ${{ github.sha }}

      #this is only used by my custom kernel module for signing the kernel to allow secure boot
      # (this simply replicates what the origami linux project does on gitlab. doing it this way means, that the build
      # still works with their gitlab pipeline and my forgejo pipeline at the same time without having to change the project itself)
      - name: Create MOK private key file
        run: |
          mkdir -p .secure_files
          echo "${{ secrets.MOK_PRIVATE_KEY }}" > .secure_files/MOK.priv
          chmod 600 .secure_files/MOK.priv

      - name: Log GitHub context
        run: |
          echo "${{ toJSON(github) }}"
          echo "${{ toJSON(matrix) }}"
          echo "${{ toJSON(forgejo) }}"

      - name: Build Image
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
          BB_BUILD_PUSH: "true"
          BB_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
          BB_USERNAME: ${{ forgejo.repository_owner }}
          BB_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
          BB_REGISTRY_NAMESPACE: ${{ forgejo.repository_owner }}
          RECIPE_PATH: ./recipes/${{ matrix.recipe }}
          RUST_LOG_STYLE: always
          CLICOLOR_FORCE: "1"
        run: |
          bluebuild build -v "${RECIPE_PATH}"
