name: bluebuild-new-method
on:
  #schedule:
  #  - cron: "0 6 * * *"
  push:
    branches:
  #    - main
      - test
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: docker
    container:
      image: ghcr.io/blue-build/cli:latest
      #options: --user root #-v /var/run/docker.sock:/var/run/docker.sock
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - base.yml
    steps:
      - name: Install node
        run: |
          dnf install -y nodejs

      - name: Checkout repository
        uses: actions/checkout@v6

      #if nodejs installation should fail, you can simply remove the installation and the checkout action above
      # and just run git commands manually (:
#      - name: Checkout repository
#        run: |
#          git clone ${{ github.server_url }}/${{ github.repository }} .
#          git checkout ${{ github.sha }}

      - name: Create MOK private key file
        run: |
          mkdir -p .secure_files
          echo "${{ secrets.MOK_PRIVATE_KEY }}" > .secure_files/MOK.priv
          chmod 600 .secure_files/MOK.priv

      - name: Build Image
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
          BB_BUILD_PUSH: "true"
          BB_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
          BB_USERNAME: ${{ github.actor }}
          BB_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
          BB_REGISTRY_NAMESPACE: ${{ github.repository_owner }}
          GH_PR_EVENT_NUMBER: ${{ github.event.number }}
          RECIPE_PATH: ./recipes/${{ matrix.recipe }}
          RUST_LOG_STYLE: always
          CLICOLOR_FORCE: "1"
        run: |
          bluebuild build -v "${RECIPE_PATH}"

