name: ISO Generation
on:
  #schedule:
  #  - cron: "0 0 1 */3 *" # Every 3 months
  workflow_dispatch:

jobs:
  generate-iso:
    name: Generate ISO
    runs-on: docker
    container:
      image: ghcr.io/blue-build/cli:latest
    steps:
      - name: Install dependencies
        run: |
          dnf install -y nodejs jq

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set Release Name
        run: |
          echo "RELEASE_TAG=$(date +%Y.%m.%d-%H%M)" >> $GITHUB_ENV

      - name: Create MOK private key file
        run: |
          mkdir -p .secure_files
          echo "${{ secrets.MOK_PRIVATE_KEY }}" > .secure_files/MOK.priv
          chmod 600 .secure_files/MOK.priv

      #- name: Generate ISO
      #  run: |
      #    bluebuild generate-iso \
      #      --secure-boot-url https://forgejo.pandabrain.com/pandabrain/pureuda-os/raw/branch/main/MOK.der \
      #      --enrollment-password bluebuild \
      #      --iso-name pureuda-os-${{ env.RELEASE_TAG }}.iso \
      #      --output-dir iso \
      #      image forgejo.pandabrain.com/pandabrain/pureuda-os:latest
      #    ls -R iso

      - name: Generate Fake ISO
        run: |
          mkdir iso
          touch iso/pureuda-os-${{ env.RELEASE_TAG }}.iso
          touch iso/pureuda-os-${{ env.RELEASE_TAG }}.iso-CHECKSUM
          ls
      - name: Generate Fake ISO
        run: |
          ls

      - name: Create Forgejo Release
        uses: actions/forgejo-release@v2.11.3
        with:
          url: https://forgejo.pandabrain.com #probably not needed
          repo: pandabrain/pureuda-os #probably not needed
          sha: ${{ github.sha }} #probably not needed
          title: "iso-${{ env.RELEASE_TAG }}"
          token: ${{ secrets.RELEASE_TOKEN }}
          direction: upload
          release-dir: iso
          release-notes: "Release ${{ env.RELEASE_TAG }}"
          tag: "${{ env.RELEASE_TAG }}"